language: python
sudo: false
dist: trusty

python:
- '2.7'
- '3.5'


cache: apt

addons:
  apt:
    packages:
    - libopenblas-dev
    - liblapack-dev
    - gfortran


before_install:
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- conda update --yes conda
- conda config --add channels jochym

install:
- conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy ase spglib scipy
- git describe --tags --dirty| sed -e 's/-g.*$//' -e 's/-/./' -e 's/^[vr]//' > __version__.txt
- python setup.py install

script: python test/test_elastic.py

env :
    global:
        secure: "GGPGaiI1BWedN5uJ2I4kLfgU3zbOCIKi3RpDVLiGKMwMAZjgkWWUC71Ui7wEm6uiXadXcO3q0Iu17KAjSDn6E0Gz7dChGraXH2vbUJN/AxTyPPh3skKxsSPRTru2fEzZkDsIo0OQWfpwtOPptiRTu5RtyfE1eoYFGSEZGi2+IUMrInakwcbeUGFF/N+TlW5cxvJo1oCdiAEwaTZPBLQQ/QTJ7uWl/cO9v5jbJ9rehpJgdYb9h8PG8U6PrIPyDDQ6/GmrCaGPJxzYwIX+mmN6kb17qpET5rvVnBl2Iq7rSKQzl/SeY4l04WXZ9vpQW4itElOqeGczEEmmrQtF1yfi0g63p8Zt0tdJEsRQvkiJvEENuW7wGm8vFngI1WNt3E6EXNc5fOUjxD95RJMcRoQBtVIgxgbRoGuU01IH6XAGN417EIaTAvwnCQ7FHJbZzIT00q57O8ge9ro/gNP6XPVaz2uvp7MsGR2wrbOxzT0mebRRGiYixNiLhJaZxBM53Wf8HYrbQzP1tv+ya9hsafu4fsI/2iSFloXYv9GK/dpL6kfYxWCfYMPi7a/gs6KouLCMrYurYYTiw2gTvpKKc6AMvisZX46Ar8m8HXjKw1pgDOzHf8elGuZEwhnZG0C57vUYXw4UPTxVIfqlK3nOR6y8mpHETm78jqiQghm5KCXjYQY="
        secure: "TxWrXGYtEmxD0JKssGzsraWxZ9cdqFGcy3wHyRiLZuXezMClJkY2ZIK7aYL5I1edV0JR3iNdNungzVImaIFTCu/35CzOIb1DJeKMUNB8Wz2FyfL1TBpLteiyTXux6ulDAzUODYVhEWPxNGuSOUujaUPbJD2Qdl/xuC2yYCSYQ/JQvsVYuIH4zjxwuhJ++T2SP2kctsFdGkiPRPTErZKCU+bWLZd1h9d9hWbi38PmSagsqP7PwMwvHDgWs0+tUcvcI45pYGbE3bJpA9VSgDejigVE5ads6c+F28NK/qTMbPVgLtI0B18qnHVMoQYBrwJtlimeEjl1+9gXpC8TfAf8gxe/wgv/UeXX6rfqcSCiC9IU/pIVLB7aifpo1wfbPs215BR+mMNM0GrUy0y6Gnhk5VETTiCqGyX+YYyMd2ELbKrhluSWifGXsHWbpsGl0Slgb617rJXa0Z7kmB311NQoIk3MXkZnGj/EC4LWHfK5LUZzirbDJxLjcuQSJN741EXg/MnDOxPWyZwBA4JV/KrwmeyUCmZNKMsTi35zk/bLRpZhngoYkqrSxn007i60ZJGfKNk4ccjZRFTEYZdikGiqH2QyvucYK5NKF11opvg5EoXD+K9UfGspQ50omd9oKIt1+xuk7CZIgTvWT/WPynAL9mjOZ+1zGM7nWNZKyppw3dA="
        secure: "Tt2x+w0DEt3+2GqdKyW/Wq/7spbWf7inNTJ8FYCR2UfQpcRBYev8MhxQ7Q7kOvaseBhPKWCnjkUhnwx1kdoC1oXVBf8MmkA/3jP6hkZ4ZgKcfBAlWK52sMZ43Ic6PxMVNMrEevgifliZuzfmsnj/mvtgLczUEIbSvqSKIPGzn2JqF7VbJlhTqdHN9WCqIhXqURwygxKNqzwwj3q5beXPMh5hF/6ry7BjjzzNUo5GKZm6AWHszSppCShBgwRg93BthDrUK6LI6onPcgsdiWG/QrO6mY9y52A7UE7BMhPNpVzrPkiRhe4qOyhDDAr86Teq4T1Yq1xRvDZFy9pkKuIlYmOxpDNG5TwCxSBMnb185G4UFfNUrZPXwevQEtqXLXwlYucnAOP2Dz+rVSsH6eYpZA3KmSwRadC0IlHf9RBEEGCrzEt6jkjhtNpCAcxbDO3gVN/WvmALUDvLH1lOvqLNkA8VvF9Nwq/wJrXQPIRX3tdiZMywElTsVoEpj9LQD4iuoLJ25k26HybbBslxsXF/svPZcAC1RL35yM046mCv0WunCAkMaSpyJU4YBwdvex75tPjtvRPWhiHZRA++NLaXNJx4uFLVIWaHwk8wNVFWvVuHnNxMVG8DAOwICElhvKVGqcatw+yn1eXN5CtH5NdOPziW5H2pZpRQtwFHpy4lggg="



deploy:
  # testing testpypi
  - provider: pypi
    skip_cleanup: true
    server: https://testpypi.python.org/pypi
    user: jochym
    password:
        secure: "y41PLkvV2+LpSmDWkaVBQyA8BE1p3mPLSaSzKn+8cZ+1hmeukqXQczum9hKfXbiIamkYc+Ri5PvWzrT1g1k4OHkOTj2m3y7HUnk50XDZ4uNvdtfmWIlOauYqXryGmDEpZN3pPE3yLIxTc4wpF8AaLnrRH7NqW0Lj/WYMJeX2fPkujY/ufBDYt4bRzFtiQISBvNJ6ZAkAVh7PH0L6kMvKYs9lZpDjs/jL8SJn9QmwIRVGZo8fwCk4Okv6bA5mLYu8CgxRDNcjMX5b6JLvKk4LG2SX9RZ3ynGBsESDf9AWoB9nJCmC4Lx5/fPZGRnyBsjMxxYuIOgqaiKIc6fKvExHFqM8c4CkItQgN/e42t6KLW3R9/JKhQrHj1rr1O1CWETWlTwv+/3zgmMddigiEdPEoCMjmIe6yUnTjGfEiUVzaOEQh+ckcuOTh0vzV4KYNBxCFLDEz2rzH+ewOjTCNhW8inCX1E9wRAhQt8mzyhq9u/IGjLZHTjQVIhEHUkQ8NB2r3ABqglM1IFhn51XsrmRSkLULZZq3Trhz0dMpZDx+XrLiQZbGqFWRgbpPbaNYLAhXHsFidarWAHUOsSzbOQy1JmkJUMDZQY0pzGTaYQeK423GkEtmQCUVjSKp4h/kvXLR597a0koruWfK006l+BQtrkrLAo4oHZw0GWbnwdsWHz4="
    on:
        branch: rc_no
        tags: false
        python: 2.7
  #custom pypitest
  - provider: script
    skip_cleanup: true
    script: bash ./pypideploy.sh https://testpypi.python.org/pypi sdist
    on:
        branch: rc
        tags: false
        python: 2.7
  # testing anaconda
  - provider: script
    skip_cleanup: true
    script: anaconda -t $ANACONDA_TOKEN build trigger --test-only --branch rc jochym/Elastic
    on:
        branch: rc
        tags: false
        python: 2.7
  # Production pypi
  - provider: pypi
    skip_cleanup: true
    user: jochym
    password:
        secure: "kwdS9crh4V2VwpuyFLJuquOeNVkHvVWvn6YbyqaUF3vvFSirHHvwzzrKgWSEJAvWseeg1KaPgi6Zsvi1CXSbHge9yC4fZfmXVn2z09KWg/m9xorZu/MkV8AG60lvtxAceFo5FE+sZws9mJW4Df0EBSY4iX7mhxOSFsE5M7Am3J9Ij3H5dNubtvUYstzeExnf6CueQZ7YE3j1bTsymglwfJ1I3pFMakRuJWqyaYAWm4ry9XX233dSL/cAD9SFwQZ+p2a0CIRcyNSjq4j2jwD79HcW69xL7oWB/z56wGyLzNkkWFac5CxW/gPYVC7Nf48An9dfryDqbT9xrwT4wK1AD5tHpb4+dHZP6GTVK58Sc/DCRfn7bNb7kdb2ftmehxw9+JTVvfDck9/msQ2QNsrRkAE5aPghgaJfVQagyIqOPjYvqJAAubfzMEvqow2TcVM0BIgcX151JD9rdSkNm94euZafzaLbJ0/+YrjzWe9sZzwxjDNtUMPLe5062GPNjuFTDYC16spMotJGGvXn3jCK1J44+pgQ53ZOhlkDfwrByyWNnmTbwjGTWuxTzrGQTHQS7enxcLuwEtTO/XYDqAnMC7H/a8m+l3k8XmCq+D94BOigEJwKtHIrADZEAwpuOx9FLiMXFwcZRhax/HsYmVOf/arDZEBwEbArsGl2ecpoSKQ="
    on:
        branch: master
        tags: false
        python: 2.7
  # production anaconda
  - provider: script
    skip_cleanup: true
    script: anaconda -t $ANACONDA_TOKEN build trigger --branch master jochym/Elastic
    on:
        branch: master
        tags: false
        python: 2.7

