language: python
sudo: false
dist: trusty

python:
- '2.7'
- '3.5'


cache: apt

addons:
  apt:
    packages:
    - libopenblas-dev
    - liblapack-dev
    - gfortran


before_install:
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- conda update --yes conda
- conda config --add channels jochym
- conda install --yes anaconda-client anaconda-build

install:
- conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy ase spglib scipy
- git describe --tags --dirty| sed -e 's/-g.*$//' -e 's/-/./' -e 's/^[vr]//' > __version__.txt
- python setup.py install

script: python test/test_elastic.py


deploy:
  # testing testpypi
  - provider: pypi
    skip_cleanup: true
    upload_docs: no
    server: https://testpypi.python.org/pypi
    user: jochym
    password:
      secure: "y41PLkvV2+LpSmDWkaVBQyA8BE1p3mPLSaSzKn+8cZ+1hmeukqXQczum9hKfXbiIamkYc+Ri5PvWzrT1g1k4OHkOTj2m3y7HUnk50XDZ4uNvdtfmWIlOauYqXryGmDEpZN3pPE3yLIxTc4wpF8AaLnrRH7NqW0Lj/WYMJeX2fPkujY/ufBDYt4bRzFtiQISBvNJ6ZAkAVh7PH0L6kMvKYs9lZpDjs/jL8SJn9QmwIRVGZo8fwCk4Okv6bA5mLYu8CgxRDNcjMX5b6JLvKk4LG2SX9RZ3ynGBsESDf9AWoB9nJCmC4Lx5/fPZGRnyBsjMxxYuIOgqaiKIc6fKvExHFqM8c4CkItQgN/e42t6KLW3R9/JKhQrHj1rr1O1CWETWlTwv+/3zgmMddigiEdPEoCMjmIe6yUnTjGfEiUVzaOEQh+ckcuOTh0vzV4KYNBxCFLDEz2rzH+ewOjTCNhW8inCX1E9wRAhQt8mzyhq9u/IGjLZHTjQVIhEHUkQ8NB2r3ABqglM1IFhn51XsrmRSkLULZZq3Trhz0dMpZDx+XrLiQZbGqFWRgbpPbaNYLAhXHsFidarWAHUOsSzbOQy1JmkJUMDZQY0pzGTaYQeK423GkEtmQCUVjSKp4h/kvXLR597a0koruWfK006l+BQtrkrLAo4oHZw0GWbnwdsWHz4="
    on:
      branch: rc
      tags: false
      python: 2.7
  # testing anaconda
  - provider: script
    skip_cleanup: true
    script: anaconda -t $ANACONDA_TOKEN build trigger --test-only --branch rc jochym/Elastic
    on:
      branch: rc
      tags: false
      python: 2.7
  # Production pypi
  - provider: pypi
    skip_cleanup: true
    user: jochym
    password:
      secure: "kwdS9crh4V2VwpuyFLJuquOeNVkHvVWvn6YbyqaUF3vvFSirHHvwzzrKgWSEJAvWseeg1KaPgi6Zsvi1CXSbHge9yC4fZfmXVn2z09KWg/m9xorZu/MkV8AG60lvtxAceFo5FE+sZws9mJW4Df0EBSY4iX7mhxOSFsE5M7Am3J9Ij3H5dNubtvUYstzeExnf6CueQZ7YE3j1bTsymglwfJ1I3pFMakRuJWqyaYAWm4ry9XX233dSL/cAD9SFwQZ+p2a0CIRcyNSjq4j2jwD79HcW69xL7oWB/z56wGyLzNkkWFac5CxW/gPYVC7Nf48An9dfryDqbT9xrwT4wK1AD5tHpb4+dHZP6GTVK58Sc/DCRfn7bNb7kdb2ftmehxw9+JTVvfDck9/msQ2QNsrRkAE5aPghgaJfVQagyIqOPjYvqJAAubfzMEvqow2TcVM0BIgcX151JD9rdSkNm94euZafzaLbJ0/+YrjzWe9sZzwxjDNtUMPLe5062GPNjuFTDYC16spMotJGGvXn3jCK1J44+pgQ53ZOhlkDfwrByyWNnmTbwjGTWuxTzrGQTHQS7enxcLuwEtTO/XYDqAnMC7H/a8m+l3k8XmCq+D94BOigEJwKtHIrADZEAwpuOx9FLiMXFwcZRhax/HsYmVOf/arDZEBwEbArsGl2ecpoSKQ="
    on:
      branch: master
      tags: false
      python: 2.7
  # production anaconda
  - provider: script
    skip_cleanup: true
    script: anaconda -t $ANACONDA_TOKEN build trigger --branch master jochym/Elastic
    on:
      branch: master
      tags: false
      python: 2.7


